// import type { NextPage } from 'next'
import Head from 'next/head'
import React, { useState } from 'react';
import Matrix from './matrix/index';
import Container from '@material-ui/core/Container';
import Typography from '@material-ui/core/Typography';
import { Box } from '@material-ui/core';

const Home = () => {

  return (
    <div >
      <Head>
        <title>My Matrix Project</title>
        <meta name="description" content="Generated by Shayan Zarbash" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth="sm">
        <main>
          <Box>
            <Typography variant="h4" gutterBottom>
              Welcome to My Matrix Project
            </Typography>
            <Matrix />
          </Box>
        </main>
      </Container>
    </div>
  )
}

export default Home
